insert into movies (title) values ('Three Brothers, The (Les trois frères)');
insert into movies (title) values ('Mole People, The');
insert into movies (title) values ('Wanted');
insert into movies (title) values ('Miss March');
insert into movies (title) values ('Midnight Run');
insert into movies (title) values ('Terrorist, The (a.k.a. Malli) (Theeviravaathi)');
insert into movies (title) values ('Age of Innocence, The');
insert into movies (title) values ('Haunted Echoes');
insert into movies (title) values ('Fear of Flying');
insert into movies (title) values ('The Count of Monte Cristo');
insert into movies (title) values ('Days of Heaven');
insert into movies (title) values ('League of Extraordinary Gentlemen, The (a.k.a. LXG)');
insert into movies (title) values ('23 Paces to Baker Street');
insert into movies (title) values ('Land That Time Forgot, The');
insert into movies (title) values ('Canadian Bacon');
insert into movies (title) values ('Affluenza');
insert into movies (title) values ('The Great Raid');
insert into movies (title) values ('Stella');
insert into movies (title) values ('Inside Moves');
insert into movies (title) values ('White Fang 2: Myth of the White Wolf');
insert into movies (title) values ('Light It Up');
insert into movies (title) values ('Wedding Belles');
insert into movies (title) values ('In the Realms of the Unreal');
insert into movies (title) values ('Police Academy 2: Their First Assignment');
insert into movies (title) values ('Can Mr. Smith Get to Washington Anymore?');
insert into movies (title) values ('Girls Town');
insert into movies (title) values ('The Loyal 47 Ronin');
insert into movies (title) values ('Titfield Thunderbolt, The');
insert into movies (title) values ('In Good Company');
insert into movies (title) values ('Lassie Come Home');
insert into movies (title) values ('Prime Suspect 7: The Final Act');
insert into movies (title) values ('Motel, The');
insert into movies (title) values ('Field, The');
insert into movies (title) values ('Fort McCoy');
insert into movies (title) values ('Deadly Blessing');
insert into movies (title) values ('Lake Mungo');
insert into movies (title) values ('We Were Here');
insert into movies (title) values ('The Little Rascals Save the Day');
insert into movies (title) values ('Brothers Rico, The');
insert into movies (title) values ('Toothless');
insert into movies (title) values ('Johnny Guitar');
insert into movies (title) values ('Square, The');
insert into movies (title) values ('American Crime, An');
insert into movies (title) values ('Angels in the Outfield');
insert into movies (title) values ('Dreamcatcher');
insert into movies (title) values ('The Golden Cage');
insert into movies (title) values ('Superproduction (Superprodukcja)');
insert into movies (title) values ('Blood Games ');
insert into movies (title) values ('Sea of Grass, The');
insert into movies (title) values ('Farewell, The (Abschied - Brechts letzter Sommer)');
insert into movies (title) values ('Joe''s Palace');
insert into movies (title) values ('Maiden''s Cheek (To xylo vgike apo ton Paradeiso)');
insert into movies (title) values ('Once My Mother');
insert into movies (title) values ('Out of Reach');
insert into movies (title) values ('Trouble with the Truth, The');
insert into movies (title) values ('Attila');
insert into movies (title) values ('SuperBabies: Baby Geniuses 2');
insert into movies (title) values ('Road to Zanzibar');
insert into movies (title) values ('Third Man, The');
insert into movies (title) values ('At First Sight (Entre Nous) (Coup de foudre)');
insert into movies (title) values ('Adventures in Zambezia');
insert into movies (title) values ('Jerk Theory, The');
insert into movies (title) values ('Three Days (Tres días)');
insert into movies (title) values ('Fool There Was, A');
insert into movies (title) values ('Restless Natives');
insert into movies (title) values ('Major League II');
insert into movies (title) values ('Tube Tales');
insert into movies (title) values ('Outside Ozona');
insert into movies (title) values ('Satan''s Sword (Daibosatsu tôge)');
insert into movies (title) values ('Moontide');
insert into movies (title) values ('Poor Boy''s Game');
insert into movies (title) values ('I Am Divine');
insert into movies (title) values ('Concursante');
insert into movies (title) values ('Bush''s Brain');
insert into movies (title) values ('Second Best');
insert into movies (title) values ('Pyramid, The');
insert into movies (title) values ('Winter''s Tale');
insert into movies (title) values ('Bang');
insert into movies (title) values ('Love Crime (Crime d''amour)');
insert into movies (title) values ('The Killers');
insert into movies (title) values ('Sergeant Körmy and the South Pacific (Vääpeli Körmy ja etelän hetelmät)');
insert into movies (title) values ('Roberta');
insert into movies (title) values ('Crawlspace');
insert into movies (title) values ('Satan''s Sword II (Daibosatsu toge: Ryujin no maki)');
insert into movies (title) values ('Chocolate Soldier, The');
insert into movies (title) values ('Storm Catcher');
insert into movies (title) values ('Blood Money');
insert into movies (title) values ('Naked Face, The');
insert into movies (title) values ('Standing Still');
insert into movies (title) values ('Innocent Sleep, The');
insert into movies (title) values ('21-87');
insert into movies (title) values ('Harley Davidson and the Marlboro Man');
insert into movies (title) values ('Super 8 Stories');
insert into movies (title) values ('Main Event, The');
insert into movies (title) values ('Jekyll & Hyde... Together Again');
insert into movies (title) values ('Python');
insert into movies (title) values ('Samurai Assassin (Samurai)');
insert into movies (title) values ('Marley & Me');
insert into movies (title) values ('Homefront');
insert into movies (title) values ('Beautiful Country, The');
