insert into "Movie" (movie_id, title, category) values (1, 'Prime of Miss Jean Brodie, The', 'Drama');
insert into "Movie" (movie_id, title, category) values (2, 'Un Poliziotto Scomodo', 'Action|Crime|Thriller');
insert into "Movie" (movie_id, title, category) values (3, 'Boy Meets Girl', 'Comedy|Romance');
insert into "Movie" (movie_id, title, category) values (4, 'First Kid', 'Children|Comedy');
insert into "Movie" (movie_id, title, category) values (5, 'Card Player, The (Il cartaio)', 'Crime|Horror|Mystery|Thriller');
insert into "Movie" (movie_id, title, category) values (6, 'Blue Valentine', 'Drama|Romance');
insert into "Movie" (movie_id, title, category) values (7, 'Enter Arsene Lupin', 'Crime|Drama');
insert into "Movie" (movie_id, title, category) values (8, 'Professor Layton and the Eternal Diva (Eiga Reiton-kyôju to eien no utahime)', 'Action|Adventure|Animation|Mystery|Sci-Fi');
insert into "Movie" (movie_id, title, category) values (9, 'A Home at the End of the World', 'Drama|Romance');
insert into "Movie" (movie_id, title, category) values (10, 'Fast & Furious (Fast and the Furious 4, The)', 'Action|Crime|Drama|Thriller');
insert into "Movie" (movie_id, title, category) values (11, 'God Bless Ozzy Osbourne', 'Documentary');
insert into "Movie" (movie_id, title, category) values (12, 'Bunnyman', 'Horror');
insert into "Movie" (movie_id, title, category) values (13, 'Pohjanmaa', 'Drama');
insert into "Movie" (movie_id, title, category) values (14, 'Lucky One, The', 'Drama');
insert into "Movie" (movie_id, title, category) values (15, 'Salvador (Puig Antich)', 'Drama');
insert into "Movie" (movie_id, title, category) values (16, 'Trapeze', 'Drama');
insert into "Movie" (movie_id, title, category) values (17, 'Richard Pryor Live on the Sunset Strip', 'Comedy|Documentary');
insert into "Movie" (movie_id, title, category) values (18, 'Who Killed Vincent Chin?', 'Crime|Documentary');
insert into "Movie" (movie_id, title, category) values (19, 'Bottle Shock', 'Drama');
insert into "Movie" (movie_id, title, category) values (20, 'Man of the Year, The (O Homem do Ano)', 'Action|Comedy|Crime');
insert into "Movie" (movie_id, title, category) values (21, 'Billy Jack Goes to Washington', 'Drama');
insert into "Movie" (movie_id, title, category) values (22, 'Scarecrows', 'Horror');
insert into "Movie" (movie_id, title, category) values (23, 'Butcher Boy, The', 'Comedy|Drama');
insert into "Movie" (movie_id, title, category) values (24, 'Play Misty for Me', 'Drama|Thriller');
insert into "Movie" (movie_id, title, category) values (25, 'Exit Smiling', 'Comedy|Romance');
insert into "Movie" (movie_id, title, category) values (26, 'Place Vendôme', 'Crime|Drama');
insert into "Movie" (movie_id, title, category) values (27, 'Valley of the Bees (Údolí vcel)', 'Drama');
insert into "Movie" (movie_id, title, category) values (28, 'Six in Paris (Paris vu par...)', 'Drama|Romance');
insert into "Movie" (movie_id, title, category) values (29, 'Unsinkable Molly Brown, The', 'Musical');
insert into "Movie" (movie_id, title, category) values (30, 'Corridors of Blood', 'Crime|Drama|Horror|Thriller');
insert into "Movie" (movie_id, title, category) values (31, 'Man Who Cried, The', 'Drama');
insert into "Movie" (movie_id, title, category) values (32, 'The Color of Milk', 'Comedy|Drama');
insert into "Movie" (movie_id, title, category) values (33, 'Heavyweights (Heavy Weights)', 'Children|Comedy');
insert into "Movie" (movie_id, title, category) values (34, 'Dead Snow 2: Red vs. Dead ', 'Action|Comedy|Horror');
insert into "Movie" (movie_id, title, category) values (35, 'Believer, The', 'Drama');
insert into "Movie" (movie_id, title, category) values (36, 'On the Line', 'Comedy|Romance');
insert into "Movie" (movie_id, title, category) values (37, 'Woman in Black, The', 'Horror|Mystery');
insert into "Movie" (movie_id, title, category) values (38, 'Tom at the Farm (Tom à la ferme)', 'Drama');
insert into "Movie" (movie_id, title, category) values (39, 'Purge (Puhdistus)', 'Drama');
insert into "Movie" (movie_id, title, category) values (40, 'Salaam-E-Ishq', 'Comedy|Drama|Musical|Romance');
insert into "Movie" (movie_id, title, category) values (41, 'Fried Green Tomatoes', 'Comedy|Crime|Drama');
insert into "Movie" (movie_id, title, category) values (42, 'Attack the Gas Station! (Juyuso seubgyuksageun)', 'Comedy|Crime');
insert into "Movie" (movie_id, title, category) values (43, 'Fortress 2', 'Action|Sci-Fi');
insert into "Movie" (movie_id, title, category) values (44, 'Bride Flight', 'Drama');
insert into "Movie" (movie_id, title, category) values (45, 'Stuff, The', 'Comedy|Horror|Mystery|Sci-Fi');
insert into "Movie" (movie_id, title, category) values (46, 'Toward the Unknown', 'Drama|Romance|War');
insert into "Movie" (movie_id, title, category) values (47, 'Robin Hood', 'Action|Adventure|Drama|Romance|War');
insert into "Movie" (movie_id, title, category) values (48, 'Between Two Worlds', 'Action|Adventure|Drama|Fantasy|Mystery');
insert into "Movie" (movie_id, title, category) values (49, 'Heiter bis wolkig', 'Comedy|Drama|Romance');
insert into "Movie" (movie_id, title, category) values (50, 'Villain, The (Le Vilain)', 'Comedy');
insert into "Movie" (movie_id, title, category) values (51, 'Where the Heart Is', 'Comedy|Drama');
insert into "Movie" (movie_id, title, category) values (52, 'Admiral Yamamoto', 'Drama|War');
insert into "Movie" (movie_id, title, category) values (53, 'Stricken (Er komt een vrouw bij de dokter)', 'Drama|Romance');
insert into "Movie" (movie_id, title, category) values (54, 'Io Island (Iodo)', 'Mystery');
insert into "Movie" (movie_id, title, category) values (55, 'PT 109', 'Drama|War');
insert into "Movie" (movie_id, title, category) values (56, '7th Dawn, The', 'Adventure|Drama|War');
insert into "Movie" (movie_id, title, category) values (57, 'Miranda', 'Comedy|Fantasy|Romance');
insert into "Movie" (movie_id, title, category) values (58, 'Promise Her Anything', 'Comedy|Drama');
insert into "Movie" (movie_id, title, category) values (59, 'Dead Times (Temps morts, Les)', 'Animation');
insert into "Movie" (movie_id, title, category) values (60, 'Secret Agent, The', 'Drama');
insert into "Movie" (movie_id, title, category) values (61, 'Gunman''s Walk ', 'Western');
insert into "Movie" (movie_id, title, category) values (62, 'I Inside, The', 'Fantasy|Mystery|Sci-Fi');
insert into "Movie" (movie_id, title, category) values (63, 'Tyler Perry''s A Madea Christmas', 'Comedy|Drama');
insert into "Movie" (movie_id, title, category) values (64, 'Class of Nuke ''Em High', 'Comedy|Horror');
insert into "Movie" (movie_id, title, category) values (65, 'Rebirth of Mothra III', 'Action|Fantasy|Sci-Fi');
insert into "Movie" (movie_id, title, category) values (66, 'The Beast Kills in Cold Blood', 'Horror|Mystery|Thriller');
insert into "Movie" (movie_id, title, category) values (67, 'Schwestern', 'Comedy');
insert into "Movie" (movie_id, title, category) values (68, 'Ecstasy (Éxtasis)', 'Drama');
insert into "Movie" (movie_id, title, category) values (69, 'Mr. Jones', 'Drama|Horror|Thriller');
insert into "Movie" (movie_id, title, category) values (70, 'Man from Monterey, The', 'Western');
insert into "Movie" (movie_id, title, category) values (71, 'All the Rage (It''s the Rage)', 'Drama');
insert into "Movie" (movie_id, title, category) values (72, 'Incredibly True Adventure of Two Girls in Love, The', 'Comedy|Romance');
insert into "Movie" (movie_id, title, category) values (73, 'Love and Death on Long Island', 'Comedy|Drama');
insert into "Movie" (movie_id, title, category) values (74, 'Stardust', 'Adventure|Comedy|Fantasy|Romance');
insert into "Movie" (movie_id, title, category) values (75, 'Wedding in Blood (Noces rouges, Les)', 'Crime|Drama');
insert into "Movie" (movie_id, title, category) values (76, 'Angels of the Universe (Englar alheimsins)', 'Drama');
insert into "Movie" (movie_id, title, category) values (77, 'Vampire Journals', 'Fantasy|Horror');
insert into "Movie" (movie_id, title, category) values (78, 'Left Hand of God, The', 'Drama');
insert into "Movie" (movie_id, title, category) values (79, 'Dead Man Down', 'Action|Crime|Drama|Romance|Thriller');
insert into "Movie" (movie_id, title, category) values (80, 'Instinct', 'Drama|Thriller');
insert into "Movie" (movie_id, title, category) values (81, 'Blacksmith Scene', '(no genres listed)');
insert into "Movie" (movie_id, title, category) values (82, 'Lovers and Lollipops', 'Drama|Romance');
insert into "Movie" (movie_id, title, category) values (83, 'Pledge, The', 'Crime|Drama|Mystery|Thriller');
insert into "Movie" (movie_id, title, category) values (84, 'Flicker', 'Horror');
insert into "Movie" (movie_id, title, category) values (85, 'Blue and the Gray, The', 'Drama|War');
insert into "Movie" (movie_id, title, category) values (86, 'My Grandfather''s People (Dedemin insanlari)', 'Comedy|Drama');
insert into "Movie" (movie_id, title, category) values (87, 'Skin', 'Drama|Mystery');
insert into "Movie" (movie_id, title, category) values (88, 'Pale Flower (Kawaita hana)', 'Crime|Film-Noir|Thriller');
insert into "Movie" (movie_id, title, category) values (89, 'Sea Hawk, The', 'Action|Adventure|Romance');
insert into "Movie" (movie_id, title, category) values (90, 'Amber Alert ', 'Thriller');
insert into "Movie" (movie_id, title, category) values (91, 'Wallace and Gromit in ''A Matter of Loaf and Death''', 'Animation|Comedy');
insert into "Movie" (movie_id, title, category) values (92, 'Oceans (Océans)', 'Documentary|Drama');
insert into "Movie" (movie_id, title, category) values (93, 'Maidens'' Conspiracy, The (Tirante el Blanco)', 'Adventure');
insert into "Movie" (movie_id, title, category) values (94, 'Daddy Long Legs', 'Musical|Romance');
insert into "Movie" (movie_id, title, category) values (95, 'Kevin Smith: Burn in Hell', 'Comedy');
insert into "Movie" (movie_id, title, category) values (96, 'Dark Horse', 'Drama');
insert into "Movie" (movie_id, title, category) values (97, 'Widows'' Peak', 'Drama');
insert into "Movie" (movie_id, title, category) values (98, 'Nicht mein Tag', 'Action|Comedy|Crime');
insert into "Movie" (movie_id, title, category) values (99, 'Barry Lyndon', 'Drama|Romance|War');
insert into "Movie" (movie_id, title, category) values (100, 'Who''s Your Daddy?', 'Comedy');
